zipkin_url: 127.0.0.1:9411
listen: :8090
period: 5s
queries:
  total_errors:
    query: "error"
    histogram_buckets: [2000.0]
  loggable_activity:
    service_name: "log-message-processor"
    histogram_buckets: [200.0, 500.0, 1000.0, 2000.0]