// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// DependencyLink DependencyLink
// swagger:model DependencyLink
type DependencyLink struct {

	// call count
	CallCount int64 `json:"callCount,omitempty"`

	// child
	Child string `json:"child,omitempty"`

	// error count
	ErrorCount int64 `json:"errorCount,omitempty"`

	// parent
	Parent string `json:"parent,omitempty"`
}

// Validate validates this dependency link
func (m *DependencyLink) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *DependencyLink) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DependencyLink) UnmarshalBinary(b []byte) error {
	var res DependencyLink
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
